---
title: "Demo analysis"
output: html_document
---

```{r}
# upload the library
library(jsonlite)
library(dplyr)
library(crosstable)
library(ggplot2)
library(nlme)
#install.packages(‘texreg’)
library(texreg)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
```


```{r}
# upload the data
c1 <- rgb(173,216,230,max = 255, alpha = 80, names = "lt.blue")
c2 <- rgb(255,192,203, max = 255, alpha = 80, names = "lt.pink")


# Descriptive statistics from our 
outDir <- "~/Github/uspto/eda/searches/"
inventors_mechanical <- read.csv(xzfile(paste0(outDir, "inventors_mechanical.csv.xz")))
inventors_pharma <- read.csv(xzfile(paste0(outDir, "inventors_pharmaceutical.csv.xz")))
inventors <- read.csv(xzfile(paste0(outDir, "inventors.csv.xz")))

# Preview of result: Gender of inventors
inventors_mechanical$gender_wgnd[inventors_mechanical$prob_fem_wgnd>0.5] <- 'Female'
inventors_mechanical$gender_wgnd[inventors_mechanical$prob_fem_wgnd<0.5] <- 'Male'
inventors_mechanical$gender_wgnd[inventors_mechanical$prob_fem_wgnd==0.5] <- 'Unknow'
inventors_mechanical$year <- as.integer(substr(inventors_mechanical$date, 1, 4))


inventors_pharma$gender_wgnd[inventors_pharma$prob_fem_wgnd>0.5] <- 'Female'
inventors_pharma$gender_wgnd[inventors_pharma$prob_fem_wgnd<0.5] <- 'Male'
inventors_pharma$gender_wgnd[inventors_pharma$prob_fem_wgnd==0.5] <- 'Unknow'
inventors_pharma$year <- as.integer(substr(inventors_pharma$date, 1, 4))
```

## Combine data
```{r}
# Descriptive statistics on gender
unique_inventor_mecha <- inventors_mechanical %>% select(fullname,gender_wgnd,inventorCountry,inventorState,inventorCity,search_set) %>% unique()
unique_inventor_pharma <- inventors_pharma %>% select(fullname,gender_wgnd,inventorCountry,inventorState,inventorCity,search_set) %>% unique()
unique_inventor <- dplyr::bind_rows(unique_inventor_mecha, unique_inventor_pharma)
```

## Crosstable
```{r}

# Analyse inventors demographics
crosstable(unique_inventor, gender_wgnd, by=search_set, total="column", margin="column")

# Focus on US inventor and analyze their gender
unique_inventor$inventorState[unique_inventor$inventorState==" CA"] <- "CA"
unique_inventor$inventorState[unique_inventor$inventorState==" NY"] <- "NY"
unique_inventor$inventorState[unique_inventor$inventorState=="WA`"] <- "WA"
Test <- crosstable(unique_inventor[unique_inventor$inventorCountry=="US",], by=gender_wgnd, inventorState, margin="column")
```


## gender score
```{r}
# create a gender score
inventors_mechanical$gender_score[inventors_mechanical$gender_wgnd=='Female'] <- 1
inventors_mechanical$gender_score[inventors_mechanical$gender_wgnd=='Male'] <- 0

inventors_pharma$gender_score[inventors_pharma$gender_wgnd=='Female'] <- 1
inventors_pharma$gender_score[inventors_pharma$gender_wgnd=='Male'] <- 0

unique_application_mecha <- inventors_mechanical %>% 
                            select(guid, applicationNumber, art_unit, status, search_set, any_accepts, year, gender_score) %>% 
                            group_by(guid, applicationNumber) %>%
                            summarize(team_size=length(guid), art_unit =art_unit, status=status, search_set=search_set, any_accepts=mean(any_accepts), year = mean(year), gender_score=mean(gender_score, na.rm =T) ) %>% unique()

unique_application_pharma <- inventors_pharma %>% 
                            select(guid, applicationNumber, art_unit, status, search_set, any_accepts, year, gender_score) %>% 
                            group_by(guid, applicationNumber) %>%
                            summarize(team_size=length(guid), art_unit =art_unit, status=status, search_set=search_set, any_accepts=mean(any_accepts), year = mean(year), gender_score=mean(gender_score, na.rm =T) ) %>% unique()


unique_application <- dplyr::bind_rows(unique_application_mecha, unique_application_pharma)
```



## Description
```{r}
# Description
test1 <- unique_application %>% filter(search_set=='mechanical') %>% group_by(team_size) %>% summarize(prob = mean(gender_score, na.rm=T))
test2 <- unique_application %>% filter(search_set=='pharmaceutical') %>% group_by(team_size) %>% summarize(prob = mean(gender_score, na.rm=T))
par(mfrow=c(1,2))
plot(test1$team_size, test1$prob, xlab='size application', ylab='% of women per application', main='Pharmaceutical')
plot(test2$team_size, test2$prob, xlab='size application', ylab='% of women per application', main='Mechanical')
```



## Distribution of applications by % of women applications
```{r}
# Distribution of applications by % of women applications
h1 <- hist(unique_application$gender_score[unique_application$search_set=='mechanical'], plot=FALSE)
h1$counts=h1$counts/sum(h1$counts)
h2 <- hist(unique_application$gender_score[unique_application$search_set=='pharmaceutical'], plot=FALSE)
h2$counts=h2$counts/sum(h2$counts)
par(mfrow=c(1,2))
plot(h1, col=c1, xlab='% of women per application', ylab='% of applications', main='Mechanical')
plot(h2, col=c1, xlab='% of women per application', ylab='% of applications', main='Pharmaceutical')
```

## Description
```{r}
# Distribution of applications by % of women applications
cdf1 <- ecdf(unique_application$team_size[unique_application$search_set=='mechanical'] )
cdf2 <- ecdf(unique_application$team_size[unique_application$search_set=='pharmaceutical'] )
par(mfrow=c(1,1))
plot(cdf1, verticals=TRUE, do.points=FALSE, col='blue', xlab='size applications', ylab='% of applications', main='Probability to have a team lower than a size')
plot(cdf2,  verticals=TRUE, do.points=FALSE, col='red', xlab='size applications', ylab='% of applications', add=T)
```



## # Do increase the team size in mechanical would increase women participation
```{r}
# Do increase the team size in mechanical would increase women participation
# Linear regression
summary(m0 <- lm(gender_score ~ team_size + search_set + any_accepts + year, data=unique_application))

# Run a poisson regression: because the gender_score follow a poisson distribution
#summary(m1a <- glm(gender_score ~ team_size, family="poisson", data=unique_application))
#summary(m1b <- glm(gender_score ~ team_size + search_set, family="poisson", data=unique_application))
#summary(m1c <- glm(gender_score ~ team_size + search_set + any_accepts, family="poisson", data=unique_application))
#summary(m1d <- glm(gender_score ~ team_size + search_set + any_accepts + year, family="poisson", data=unique_application))
#summary(m1e <- glm(gender_score ~ team_size + search_set + team_size*search_set + any_accepts + year, family="poisson", data=unique_application))
#summary(m1f <- glm(gender_score ~ team_size + search_set + team_size*search_set + any_accepts + search_set*year, family="poisson", data=unique_application))

#table.string <- texreg(list(m1a, m1b, m1c, m1d, m1e, m1f), single.row = TRUE, return.string = TRUE)
#cat(table.string)
```


## Description
```{r}
# Gender trends
trends <- unique_application %>% select(guid,year,search_set,gender_score) %>% group_by(search_set,year) %>% summarize(number_app=length(guid), average_prob=mean(gender_score, na.rm =T)) %>% unique()
plot(trends$year[trends$search_set=='mechanical'], trends$number_app[trends$search_set=='mechanical'], type="l", xlab="Year", ylab="Number of application", main='Mechanical')
plot(trends$year[trends$search_set=='mechanical'], trends$average_prob[trends$search_set=='mechanical'], type="l", xlab="Year", ylab="average proportion of women per application", main='Mechanical')

plot(trends$year[trends$search_set=='pharmaceutical'], trends$number_app[trends$search_set=='pharmaceutical'], type="l", xlab="Year", ylab="Number of application", main='pharmaceutical')
plot(trends$year[trends$search_set=='pharmaceutical'], trends$average_prob[trends$search_set=='pharmaceutical'], type="l", xlab="Year", ylab="average proportion of women per application", main='pharmaceutical')
```
