---
title: "descriptive analysis"
output: html_document
---

## Load library
```{r}
# upload library
library(jsonlite)
library(dplyr)
library(crosstable)
library(ggplot2)
library(nlme)
#install.packages(‘texreg’)
library(texreg)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(coefplot)
library(jtools)
library(ggstance)
library(tidyr)
library(usmap) #import the package
library(ggplot2) #use ggplot2 to add layer for visualization
library(mapview)
#0library(sf)
library(PNWColors)
library(transformr)
```

## Uplaod and combine data
```{r}
# upload the data
inventor_pharma <- read.csv("/project/biocomplexity/sdad/projects_data/uspto/PatentsView/working/pharma_pat_inv_loc.csv")
inventor_pharma$field <- "pharmaceuticals"
inventor_civil<- read.csv("/project/biocomplexity/sdad/projects_data/uspto/PatentsView/working/civil_pat_inv_loc.csv")
inventor_civil$field <- "civil engineering"

# combine the two data
inventor <- dplyr::bind_rows(inventor_civil, inventor_pharma)
inventor$female_flag <- 1-inventor$male_flag
inventor$gender[inventor$male_flag==1] <- "male"
inventor$gender[inventor$male_flag==0] <- "female"
inventor <- inventor %>% mutate(gender = ifelse(is.na(gender), 'unknown', gender))
```

```{r}
# number of patent by inventors+location over time.
inventor_prod <- inventor %>% 
  select(inventor_id,location_id,patent_id,gender,year,field,country,state) %>% 
  group_by(inventor_id,location_id,gender,year,field,country,state) %>% 
  mutate(number_patent=length(unique(patent_id)), .keep = "unused") %>% 
  unique()

# country status
inventor_prod$origin <- "foreign"
inventor_prod$origin[inventor_prod$country=="US"] <- "US"

# group date by period
inventor_prod <- inventor_prod %>% mutate(period=cut(year, breaks=c(1975, 1990, 2000, 2010,2021), labels=c("1976-1990","1990-2000","2000-2010","2010-2021")))
```

## gender distribution by fields
```{r}
# gender distribution by fields
inventor_desc <- inventor_prod %>% 
  select(inventor_id,gender,field) %>% 
  unique()

crosstable(inventor_desc, gender, by=field, total= "all", margin="column")
```

```{r}
# gender distribution by fields in US
inventor_desc <- inventor_prod %>%
  select(inventor_id,origin,gender,field) %>% 
  unique()

crosstable(inventor_desc, gender, by=c(field,origin), total= "all", margin="column")
```

```{r}
# patents productivity by gender.
inventor_US <- inventor_prod %>% 
  filter(origin=="US")

inventor_US %>%                               # Summary by group using dplyr
  group_by(field,gender) %>% 
  summarize(min = min(number_patent),
            q1 = quantile(number_patent, 0.25),
            median = median(number_patent),
            mean = mean(number_patent),
            q3 = quantile(number_patent, 0.75),
            max = max(number_patent))

```

## gender distribution by states in US.
```{r}
# select the package for the map
states <- us_map(regions = "states") %>% select(abbr,fips)
all_states <- unique(states$abbr)
```


```{r}
# proportion of mean and women across fields
#inventor_desc <- inventor_US %>% select(inventor_id,location_id,gender,field,state,number_patent) %>% unique()

#select only US inventors
inventor_desc <- inventor_US %>% 
  select(inventor_id,state,field,gender,number_patent) %>% 
  group_by(state,field,gender) %>% 
  summarize(number_inventor=length(unique(inventor_id)),
         avg_number_patent=mean(number_patent),
         .groups = 'drop') %>% 
  unique() 

# only keep states that would show up on the maps
inventor_desc <- inventor_desc %>% filter(state %in% all_states) 

# reshape wide and compute the gender ratio
inventor_desc01 <- inventor_desc %>% 
  select(state,field,gender,number_inventor) %>%
  pivot_wider(names_from = gender, values_from = number_inventor)

colnames(inventor_desc01) <- c("state","field","number_inventor_female", "number_inventor_male","number_inventor_unknow")

inventor_desc02 <- inventor_desc %>% 
  select(state,field,gender,avg_number_patent) %>%
  pivot_wider(names_from = gender, values_from = avg_number_patent)

colnames(inventor_desc02) <- c("state","field","avg_number_patent_female", "avg_number_patent_male","avg_number_patent_unknow")

inventor_desc <- merge(inventor_desc01, inventor_desc02, by.x = c("state","field"), by.y = c("state","field"), all.x = TRUE)

# compute the proportion of female
inventor_desc$total <- inventor_desc$number_inventor_female + inventor_desc$number_inventor_male
inventor_desc$gender_ratio <- inventor_desc$number_inventor_male/inventor_desc$number_inventor_female
inventor_desc$prop_female <- inventor_desc$number_inventor_female/inventor_desc$total
inventor_desc$prod_ratio <- inventor_desc$avg_number_patent_female/inventor_desc$avg_number_patent_male
```


```{r}
#scale_fill_gradientn(colours = pnw_palette("Bay", n=100, type="continuous"), name="Proportion of female inventors") 
# use of us_map for plotting
plot_usmap(data = inventor_desc, values = "total") + 
  labs(title ="Total number of inventors") + 
  scale_fill_gradientn(colours = adjustcolor(c("green","blue","yellow","red"), alpha.f = 0.7), name="Number of inventors") + 
  theme(legend.position = "right") + 
  facet_wrap(~field)
```


```{r}
#scale_fill_gradientn(colours = pnw_palette("Bay", n=100, type="continuous"), name="Proportion of female inventors") 
# use of us_map for plotting
plot_usmap(data = inventor_desc, values = "prop_female") + 
  labs(title ="Proportion of womens inventors") + 
  scale_fill_gradientn(colours = adjustcolor(c("green","blue","yellow","red"), alpha.f = 0.7), name="Proportion of female inventors") + 
  theme(legend.position = "right") + 
  facet_wrap(~field)
```

```{r}
#scale_fill_gradientn(colours = pnw_palette("Bay", n=100, type="continuous"), name="Proportion of female inventors") 
# use of us_map for plotting
plot_usmap(data = inventor_desc, values = "prod_ratio") + 
  labs(title ="Gender productivity ratio= average number patent (female)/average number patent (male)") + 
  scale_fill_gradientn(colours = adjustcolor(c("green","blue","yellow","red"), alpha.f = 0.7), name="gender productivity ratio") + 
  theme(legend.position = "right") + 
  facet_wrap(~field)
```

```{r}
library(ggplot2)
library(ggrepel)

# use of us_map for plotting
subset <- inventor_desc[inventor_desc$field=="pharmaceuticals",]
ggplot(subset, aes(prop_female,prod_ratio)) + 
  geom_point(color='blue') + 
  labs(x = "proportion of female", y = "gender productivity ratio") + 
  geom_text_repel(aes(label = state)) #+ geom_smooth(method = "lm", se = FALSE)

subset <- inventor_desc[inventor_desc$field=="civil engineering",]
ggplot(subset, aes(prop_female,prod_ratio)) + 
  geom_point(color='blue') + 
  labs(x = "proportion of female", y = "gender productivity ratio") + 
  geom_text_repel(aes(label = state)) #+ geom_smooth(method = "lm", se = FALSE)

```

## Trends analysis
```{r}
# proportion of mean and women across fields
inventor_desc <- inventor_US %>% 
  select(inventor_id,state,field,gender,number_patent,period) %>% 
  group_by(state,field,gender,period) %>% 
  summarize(number_inventor=length(unique(inventor_id)),
            avg_number_patent=mean(number_patent),
         .groups = 'drop') %>% 
  unique() 

# only keep states that would show up on the maps
inventor_desc <- inventor_desc %>% filter(state %in% all_states) 

# reshape wide and compute the gender ratio
inventor_desc01 <- inventor_desc %>% 
  select(state,field,gender,period,number_inventor) %>%
  pivot_wider(names_from = gender, values_from = number_inventor)

colnames(inventor_desc01) <- c("state","field","period","number_inventor_female", "number_inventor_male","number_inventor_unknow")

inventor_desc02 <- inventor_desc %>% 
  select(state,field,gender,period,avg_number_patent) %>%
  pivot_wider(names_from = gender, values_from = avg_number_patent)

colnames(inventor_desc02) <- c("state","field","period","avg_number_patent_female", "avg_number_patent_male","avg_number_patent_unknow")

inventor_desc <- merge(inventor_desc01, inventor_desc02, by.x = c("state","field","period"), by.y = c("state","field","period"), all.x = TRUE)

# compute the proportion of female
inventor_desc$total <- inventor_desc$number_inventor_female + inventor_desc$number_inventor_male
inventor_desc$gender_ratio <- inventor_desc$number_inventor_male/inventor_desc$number_inventor_female
inventor_desc$prop_female <- inventor_desc$number_inventor_female/inventor_desc$total
inventor_desc$prod_ratio <- inventor_desc$avg_number_patent_female/inventor_desc$avg_number_patent_male
```


```{r}
# use of us_map for plotting
plot_usmap(data = inventor_desc[inventor_desc$field=="pharmaceuticals",], values = "prop_female") + 
  labs(title ="Proportion of womens inventors (In pharmaceuticals)") + 
  scale_fill_gradientn(colours = adjustcolor(c("green","blue","yellow","red"), alpha.f = 0.7), name="Proportion of female inventors") + 
  theme(legend.position = "right") + 
  facet_wrap(~period)
```

```{r}
# use of us_map for plotting
plot_usmap(data = inventor_desc[inventor_desc$field=="civil engineering",], values = "prop_female") + 
  labs(title ="Proportion of womens inventors (In civil engineering)") + 
  scale_fill_gradientn(colours = adjustcolor(c("green","blue","yellow","red"), alpha.f = 0.7), name="Proportion of female inventors") + 
  theme(legend.position = "right") + 
  facet_wrap(~period)
```


```{r}
# use of us_map for plotting
plot_usmap(data = inventor_desc[inventor_desc$field=="pharmaceuticals",], values = "prod_ratio") + 
  labs(title ="Gender productivity ratio (In pharmaceuticals) = average number patent (female)/average number patent (male)") + 
  scale_fill_gradientn(colours = adjustcolor(c("green","blue","yellow","red"), alpha.f = 0.7), name="gender productivity ratio") + 
  theme(legend.position = "right") + 
  facet_wrap(~period)
```


```{r}
# use of us_map for plotting
plot_usmap(data = inventor_desc[inventor_desc$field=="civil engineering",], values = "prod_ratio") + 
  labs(title ="Gender productivity ratio (In civil engineering) = average number patent (female)/average number patent (male)") + 
  scale_fill_gradientn(colours = adjustcolor(c("green","blue","yellow","red"), alpha.f = 0.7), name="gender productivity ratio") + 
  theme(legend.position = "right") + 
  facet_wrap(~period)
```
